### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by jindrichmynarz** [OpenDataNode/UVPlugin-executeShellScript#1]
With the [current documentation](https://github.com/OpenDataNode/UVPlugin-executeShellScript/blob/develop/README.md) it is basically impossible to run this DPU. One has to look into the source code and study debug messages to understand at least several points:
1. "Script name" (which is actually "script path") must be an absolute path to the script. Using a script name symlinked to `/usr/bin` doesn't work. For example, `unzip` doesn't work, while `/usr/bin/unzip` works.
2. The executed script must be prepared to expect 3 positional arguments: configuration, list of files, and output directory.
3. List of files provided as the second argument is a plain text document with an absolute file path per line.
4. Why is the "Output directory" parameter required if the result goes to the `filesOutput` FilesDataUnit? Just put the output in `/tmp` and don't bother the user.
5. Plus, it would be nice if script location in the ODN files structure would be recommended.

**Comment by skrchnavy** [comment]
New form of documentation (About.md) to be supported.

**Comment by skrchnavy** [comment]
@jindrichmynarz please split this issue into 'Documentation bugs' (this issue) and 'Functional bugs' (new issues to be created)

**Comment by jindrichmynarz** [comment]
Since there is almost no documentation, it is hard to tell what is a bug and what is a feature. For example, is not supporting symlinked scripts a bug? However, I think the other points I raised are related to documentation, so I believe we can address them here.

**Comment by skrchnavy** [comment]
ad 1) **_BUG_**, shall be tracked as new issue, needs discussion to avoid security holes (must not run all scripts just allowed)
ad 2) need to be documented
ad 3) to be documented or to update requirement
ad 4) DPU has it's own working place, it must not be tmp dir. It is good to require that script places data into defined dir. But this must not be DPU configuration parameter but to be generated in DPU internally. **_BUG_**
ad 5) **_BUG_**, related to 1), script location shall be configurable with default in UV workspace.

**Comment by jindrichmynarz** [comment]
I have split 2 issues out of this one. Let's keep this issue for improving the documentation.

**Comment by skrchnavy** [comment]
issue moved to UnifiedViews/Plugins#331
