### ISSUE TITLE
Move the plugin to UV-Plugins, as this is not anyhow related just to ODN

### ISSUE THREAD

**Issue by tomas-knap** [OpenDataNode/UVPlugin-executeShellScript#4]
@peterklimo , why this DPU was placed to OpenDataNode repo?

**Comment by peterklimo** [comment]
relocated by 
https://github.com/OpenDataNode/ODN-UV-Plugins/commit/a72f304fe92609b3a6878dfe55f36c58d4bd0763
https://github.com/UnifiedViews/Plugins/commit/2b2749d865569da2eb808ea8255df14034ea4879

**Comment by skrchnavy** [comment]
Code migrated, issues created
UnifiedViews/Plugins#329
UnifiedViews/Plugins#330
UnifiedViews/Plugins#331
